# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_DLxt0CHHDVs2zZx7FbqTFqw-wMDKjZ
"""

import pandas as pd

"""1. Creating DataFrames"""

# Creating DataFrame from dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)

# Reading from a CSV file
data = pd.read_csv('housing_prices.csv')

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)

df.columns

"""2. Basic Operations"""

# Display the first few rows of the DataFrame
print(df.head())

# Descriptive statistics of numerical columns
print(df.describe())

# Accessing specific columns
print(df['Price'])  # Accessing the 'Price' column
print(df[['Price', 'Area', 'No. of Bedrooms']])  # Accessing multiple columns

print(df['Price'])  # Accessing the 'Price' column
print(df.loc[0])  # Accessing the first row

# Visualization
df['Price'].plot(kind='hist')  # Plotting a histogram for prices

"""3. Handling Missing Data"""

# Handling Missing Data
print(df.isnull().sum())  # Check for missing values
clean_data = df.dropna()  # Dropping rows with missing values

"""4.Descriptive Statistics"""

# Descriptive Statistics
print(df.describe())  # Summary statistics
print(df['Area'].mean())  # Mean of the 'Area' column

"""5.Data Cleaning"""

# Data Cleaning
clean_data = df.drop_duplicates()  # Remove duplicate rows
clean_data = df.rename(columns={'No. of Bedrooms': 'Bedrooms'})  # Renaming columns

"""6.Data Selection"""

# Data Selection
resale_properties = df[df['Resale'] == 1]  # Filtering based on condition

"""7.Grouping and Aggregating"""

# Grouping and Aggregating
mean_price_by_bedrooms = df.groupby('No. of Bedrooms')['Price'].mean()
print(mean_price_by_bedrooms)

"""8.Working with Text Data"""

# Working with Text Data
df['Location'] = df['Location'].str.upper()  # Converting text to uppercase
df['Location'] = df['Location'].str.replace('Location', 'Area')  # Replacing text
print(df)

"""9.Plotting and Visualization"""

# Plotting and Visualization
import matplotlib.pyplot as plt
df['Price'].plot(kind='hist')  # Plotting a histogram for prices
plt.xlabel('Price')
plt.show()

"""10.Handling Categorical Data"""

# Handling Categorical Data
df['Location'] = df['Location'].astype('category')  # Converting 'Location' to categorical data type
print(df)

"""11.Applying Functions"""

# Applying Functions
def price_category(price):
    if price > 150000:
        return 'High'
    elif price > 120000:
        return 'Medium'
    else:
        return 'Low'

df['Price_Category'] = df['Price'].apply(price_category)  # Applying function on 'Price' column
print(df)